
import { GoogleGenAI, Type, GenerateContentResponse } from "@google/genai";
import { NewsEvent, ImpactAnalysis } from "../types";

const API_KEY = process.env.GEMINI_API_KEY || "";

export class GeminiMacroService {
  private ai: GoogleGenAI;

  constructor() {
    if (!API_KEY) {
      console.warn("GEMINI_API_KEY is missing. The application will not be able to fetch real-time data.");
    }
    this.ai = new GoogleGenAI({ apiKey: API_KEY });
  }

  async monitorGlobalMarkets(queries: string[]): Promise<NewsEvent[]> {
    const prompt = `
      Search for the latest critical macro-economic news for the following topics.
      Topics: ${queries.join(", ")}
      
      IMPORTANT: 
      - Do NOT quote sources directly. 
      - PARAPHRASE all information in your own words to avoid recitation blocks.
      - Synthesize the core essence of the news.
      
      For each event:
      1. Categorize strictly into one of: 'Geopolitical Risk', 'Economic Policy Change', 'Supply Chain Disruption', 'Technological Advancement', 'Environmental Regulation'.
      2. Provide a sentiment score between -1.0 (extremely negative) and 1.0 (extremely positive).
      3. Identify relevant stock tickers (e.g., AAPL, TSLA, ASML).

      Return the data in a structured JSON format.
    `;

    const config = {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            id: { type: Type.STRING },
            translatedTitle: { type: Type.STRING, description: "A paraphrased title in English" },
            source: { type: Type.STRING },
            country: { type: Type.STRING },
            language: { type: Type.STRING },
            category: { type: Type.STRING },
            sentiment: { type: Type.NUMBER },
            timestamp: { type: Type.STRING },
            summary: { type: Type.STRING, description: "A synthesized summary in your own words" },
            relatedTickers: { type: Type.ARRAY, items: { type: Type.STRING } }
          },
          required: ["id", "translatedTitle", "summary", "category", "sentiment"]
        }
      }
    };

    try {
      const response = await this.ai.models.generateContent({
        model: 'gemini-3.1-pro-preview',
        contents: prompt,
        config: {
          ...config,
          tools: [{ googleSearch: {} }],
          toolConfig: { includeServerSideToolInvocations: true }
        }
      });

      const text = response.text;
      
      if (!text) {
        // Check if there are parts but no text getter result
        const parts = response.candidates?.[0]?.content?.parts;
        if (parts && parts.length > 0) {
          const textPart = parts.find(p => p.text);
          if (textPart && textPart.text) {
            const cleanedText = textPart.text.replace(/^```json\n?|\n?```$/g, '').trim();
            return JSON.parse(cleanedText);
          }
        }
        const finishReason = response.candidates?.[0]?.finishReason;
        throw new Error(`No content generated by the model. Finish Reason: ${finishReason || "UNKNOWN"}. This may be due to safety filters or tool grounding issues.`);
      }

      const cleanedText = text.replace(/^```json\n?|\n?```$/g, '').trim();
      return JSON.parse(cleanedText);
    } catch (error: any) {
      const errorMsg = error.message || String(error);
      const isQuotaError = errorMsg.includes('429') || 
                          errorMsg.includes('RESOURCE_EXHAUSTED') || 
                          errorMsg.includes('quota') ||
                          errorMsg.includes('limit') ||
                          errorMsg.includes('RECITATION');

      if (isQuotaError) {
        console.warn("Search grounding quota or recitation block hit. Falling back to internal knowledge...");
        const fallbackResponse = await this.ai.models.generateContent({
          model: 'gemini-3.1-pro-preview',
          contents: prompt + "\n(Note: Search tool is currently unavailable. Use your internal knowledge to provide the most recent significant macro events for these topics. Mark each event as a fallback.)",
          config
        });

        const fallbackText = fallbackResponse.text;
        if (fallbackText) {
          const cleanedText = fallbackText.replace(/^```json\n?|\n?```$/g, '').trim();
          const events: NewsEvent[] = JSON.parse(cleanedText);
          return events.map(e => ({ ...e, isFallback: true }));
        }
      }

      console.error("Error monitoring markets:", error);
      throw error;
    }
  }

  async analyzeRippleEffect(event: NewsEvent, sector: string): Promise<ImpactAnalysis> {
    const prompt = `
      Analyze the "Ripple Effect" of this specific news event on the target sector:
      Event: ${event.translatedTitle} (${event.summary})
      Country of Origin: ${event.country}
      Target Sector: ${sector}
      Sentiment: ${event.sentiment}
      
      IMPORTANT: 
      - Do NOT quote sources directly. 
      - PARAPHRASE all information in your own words to avoid recitation blocks.
      - Synthesize the core essence of the news.
      
      Explain the logical chain of causality (the ripple). Identify specific companies and market indices affected.
      Provide real-time market reaction estimates based on current trends.
    `;

    const config = {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          eventName: { type: Type.STRING },
          affectedSectors: { type: Type.ARRAY, items: { type: Type.STRING } },
          rippleChain: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                stage: { type: Type.STRING },
                description: { type: Type.STRING },
                impactLevel: { type: Type.STRING },
                targetSector: { type: Type.STRING }
              }
            }
          },
          overallRiskScore: { type: Type.NUMBER },
          marketCorrelation: { type: Type.STRING },
          marketReaction: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                symbol: { type: Type.STRING },
                companyName: { type: Type.STRING },
                estimatedImpact: { type: Type.NUMBER },
                reasoning: { type: Type.STRING }
              }
            }
          }
        },
        required: ["eventName", "rippleChain", "overallRiskScore", "marketReaction"]
      }
    };

    try {
      const response = await this.ai.models.generateContent({
        model: 'gemini-3.1-pro-preview',
        contents: prompt,
        config: {
          ...config,
          tools: [{ googleSearch: {} }],
          toolConfig: { includeServerSideToolInvocations: true }
        }
      });

      const text = response.text;
      if (!text) {
        // Check if there are parts but no text getter result
        const parts = response.candidates?.[0]?.content?.parts;
        if (parts && parts.length > 0) {
          const textPart = parts.find(p => p.text);
          if (textPart && textPart.text) {
            const cleanedText = textPart.text.replace(/^```json\n?|\n?```$/g, '').trim();
            return JSON.parse(cleanedText);
          }
        }
        const finishReason = response.candidates?.[0]?.finishReason;
        throw new Error(`No analysis generated by the model. Finish Reason: ${finishReason || "UNKNOWN"}. This may be due to safety filters or tool grounding issues.`);
      }

      const cleanedText = text.replace(/^```json\n?|\n?```$/g, '').trim();
      return JSON.parse(cleanedText);
    } catch (error: any) {
      const errorMsg = error.message || String(error);
      const isQuotaError = errorMsg.includes('429') || 
                          errorMsg.includes('RESOURCE_EXHAUSTED') || 
                          errorMsg.includes('quota') ||
                          errorMsg.includes('limit') ||
                          errorMsg.includes('RECITATION');

      if (isQuotaError) {
        console.warn("Search grounding quota or recitation block hit for analysis. Falling back to internal knowledge...");
        const fallbackResponse = await this.ai.models.generateContent({
          model: 'gemini-3.1-pro-preview',
          contents: prompt + "\n(Note: Search tool is currently unavailable. Use your internal knowledge to provide the most accurate ripple analysis based on historical trends. Mark as fallback.)",
          config
        });

        const fallbackText = fallbackResponse.text;
        if (fallbackText) {
          const cleanedText = fallbackText.replace(/^```json\n?|\n?```$/g, '').trim();
          const analysis: ImpactAnalysis = JSON.parse(cleanedText);
          return { ...analysis, isFallback: true };
        }
      }

      console.error("Error analyzing ripple effect:", error);
      throw error;
    }
  }
}
